// layout.js
import React from "react";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href={"/"}>Main</Link>
          { "   "}
          <Link href={"/about"}>About</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
